/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as SpeciesSlugRouteImport } from './routes/species.$slug'
import { Route as StrategiesIndexRouteImport } from './routes/strategies.index'
import { Route as StrategiesSlugRouteImport } from './routes/strategies.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesSlugRoute = SpeciesSlugRouteImport.update({
  id: '/species/$slug',
  path: '/species/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StrategiesRoute,
} as any)
const StrategiesSlugRoute = StrategiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StrategiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/identify': typeof IdentifyRoute
  '/saved': typeof SavedRoute
  '/strategies': typeof StrategiesRouteWithChildren
  '/species/$slug': typeof SpeciesSlugRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/strategies/': typeof StrategiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/identify': typeof IdentifyRoute
  '/saved': typeof SavedRoute
  '/species/$slug': typeof SpeciesSlugRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/strategies': typeof StrategiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/identify': typeof IdentifyRoute
  '/saved': typeof SavedRoute
  '/strategies': typeof StrategiesRouteWithChildren
  '/species/$slug': typeof SpeciesSlugRoute
  '/strategies/$slug': typeof StrategiesSlugRoute
  '/strategies/': typeof StrategiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/identify'
    | '/saved'
    | '/strategies'
    | '/species/$slug'
    | '/strategies/$slug'
    | '/strategies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/identify'
    | '/saved'
    | '/species/$slug'
    | '/strategies/$slug'
    | '/strategies'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/identify'
    | '/saved'
    | '/strategies'
    | '/species/$slug'
    | '/strategies/$slug'
    | '/strategies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  IdentifyRoute: typeof IdentifyRoute
  SavedRoute: typeof SavedRoute
  StrategiesRoute: typeof StrategiesRouteWithChildren
  SpeciesSlugRoute: typeof SpeciesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$slug': {
      id: '/species/$slug'
      path: '/species/$slug'
      fullPath: '/species/$slug'
      preLoaderRoute: typeof SpeciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/'
      fullPath: '/strategies/'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof StrategiesRoute
    }
    '/strategies/$slug': {
      id: '/strategies/$slug'
      path: '/$slug'
      fullPath: '/strategies/$slug'
      preLoaderRoute: typeof StrategiesSlugRouteImport
      parentRoute: typeof StrategiesRoute
    }
  }
}

interface StrategiesRouteChildren {
  StrategiesSlugRoute: typeof StrategiesSlugRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
}

const StrategiesRouteChildren: StrategiesRouteChildren = {
  StrategiesSlugRoute: StrategiesSlugRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
}

const StrategiesRouteWithChildren = StrategiesRoute._addFileChildren(
  StrategiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  IdentifyRoute: IdentifyRoute,
  SavedRoute: SavedRoute,
  StrategiesRoute: StrategiesRouteWithChildren,
  SpeciesSlugRoute: SpeciesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
